language: python
python:
  - "3.7"
  - "3.8"

dist: bionic

env:
  global:
    - CPLUS_INCLUDE_PATH=/usr/include/gdal
    - C_INCLUDE_PATH=/usr/include/gdal

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get -y install libgdal-dev=3.0.2+dfsg-1~bionic2

install:
  - pip install -e .
  - pip install flake8 coverage coveralls mock

# command to run tests
script:
  - flake8 . scripts/flint
  - nosetests --with-coverage --cover-package=ds --cover-package=modules --nologcapture

notifications:
  email:
    - julien.baley@gmail.com

after_success:
  - coverage combine
  - coveralls
