language: python
python:
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - apt-get install libgdal-dev
  - pip install -e .
  - pip install flake8 coverage coveralls mock

# command to run tests
script:
  - flake8 . scripts/flint
  - nosetests --with-coverage --cover-package=ds --cover-package=modules --nologcapture

notifications:
  email:
    - julien.baley@gmail.com

after_success:
  - coverage combine
  - coveralls

env:
  global:
    # AWS credentials (ID , Key)
    - CPLUS_INCLUDE_PATH=/usr/include/gdal
    - C_INCLUDE_PATH=/usr/include/gdal
