language: python
python:
  - "3.7"

dist: bionic

env:
  global:
    - CPLUS_INCLUDE_PATH=/usr/include/gdal
    - C_INCLUDE_PATH=/usr/include/gdal

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get -y install libgdal-dev=3.0.4+dfsg-1~bionic0

install:
  - cd third-party && ./INSTALL && cd ..
  - pip install -e .
  - pip install flake8 coverage coveralls mock

# command to run tests
script:
  - flake8 ds/ test/
  - nosetests --with-coverage --cover-package=ds --cover-package=modules --nologcapture

notifications:
  email:
    - julien.baley@gmail.com

after_success:
  - coverage combine
  - coveralls
